# Form implementation generated from reading ui file 'designer/mark.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QTinput = QtWidgets.QLineEdit(self.centralwidget)
        self.QTinput.setGeometry(QtCore.QRect(160, 390, 411, 41))
        self.QTinput.setObjectName("QTinput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 390, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.confirm_input = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_input.setGeometry(QtCore.QRect(600, 390, 120, 41))
        self.confirm_input.setObjectName("confirm_input")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(300, 460, 150, 41))
        self.next.setObjectName("next")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(550, 460, 150, 41))
        self.delete_2.setObjectName("delete_2")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(50, 460, 150, 41))
        self.confirm.setObjectName("confirm")
        self.QToutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.QToutput.setGeometry(QtCore.QRect(420, 111, 300, 221))
        self.QToutput.setObjectName("QToutput")
        self.showImage = QtWidgets.QLabel(self.centralwidget)
        self.showImage.setGeometry(QtCore.QRect(50, 50, 350, 300))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.showImage.setFont(font)
        self.showImage.setText("")
        self.showImage.setObjectName("showImage")
        self.QTselect_dir = QtWidgets.QPushButton(self.centralwidget)
        self.QTselect_dir.setGeometry(QtCore.QRect(590, 10, 120, 41))
        self.QTselect_dir.setObjectName("QTselect_dir")
        self.QTselect_dir_2 = QtWidgets.QPushButton(self.centralwidget)
        self.QTselect_dir_2.setGeometry(QtCore.QRect(590, 60, 120, 41))
        self.QTselect_dir_2.setObjectName("QTselect_dir_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.confirm_input.clicked.connect(MainWindow.get_input) # type: ignore
        self.confirm.clicked.connect(MainWindow.confirm_imf) # type: ignore
        self.next.clicked.connect(MainWindow.next_img) # type: ignore
        self.delete_2.clicked.connect(MainWindow.delete) # type: ignore
        self.QTselect_dir.clicked.connect(MainWindow.select_image_dir) # type: ignore
        self.QTselect_dir_2.clicked.connect(MainWindow.select_image_out) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "输入图片标签"))
        self.confirm_input.setText(_translate("MainWindow", "确定"))
        self.next.setText(_translate("MainWindow", "下一张"))
        self.delete_2.setText(_translate("MainWindow", "删除图片"))
        self.confirm.setText(_translate("MainWindow", "确认录入"))
        self.QTselect_dir.setText(_translate("MainWindow", "选择图片文件夹"))
        self.QTselect_dir_2.setText(_translate("MainWindow", "选择目标文件夹"))
